# Site settings
##The website title
name: James Morgan's Blog

##Some frequently used keywords on your website
keywords: DotNet, coding, programming, csharp, aspdotnet, python

##define base_url for valid usage in sitemap.xml and robots.txt
base_url: http://jmrgn.github.io

##define this for disqus comment support
disqus: jmrgn

##The website description (to be used in meta tags)
description: A tech blog on software development and all things related, authored by coder James Morgan
logo_location: "http://placehold.it/100x100&text=LOGO"

base_url: http://jmrgn.github.io
#url: "" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet

##Some commonly used links
links:
  twitter: jmrgn
  email: j.a.mrgn@gmail.com
  github: jmrgn

#Other Global Configuration
exclude: ['README.md']
